name = "کارنامه"
description = "دستیار مطمئن شما در خرید و فروش"
keywords = "Karnameh, used cars, car buying assistant, AI car evaluation, vehicle inspection, automotive"
image = "logo.png"
theme = "dark"
primary_color = "#00A754"
text_align = "center"
gtag_id = "AW-16482489433"
base_url = "https://karnameh-tech.github.io/"

[[sections]]
title = "پروژه‌ها"
description = "برخی از پروژه‌های متن‌باز ما در گیت‌هاب"
direction = "column"
item_style = "outline"
icon_size = "30px"
[[sections.items]]
icon = ""
title = "django-keycloak-oidc"
url = "https://github.com/karnameh-tech/django-keycloak-oidc"
description = "Fork of mozilla-django-oidc and modified to map keycloak roles / groups to django user permissions / groups."
[[sections.items]]
icon = ""
title = "Djson-form"
url = "https://github.com/karnameh-tech/djson-form"
description = "Easily generate forms for Django JSONField in admin"

[[sections]]
title = "لینک‌ها"
description = "ما را در لینک‌های زیر پیدا کنید"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = ""
title = "سایت کارنامه"
url = "https://karnameh.com"
[[sections.items]]
icon = ""
title = "فرصت‌های شغلی"
url = "https://careers.karnameh.com/"
[[sections.items]]
icon = ""
title = "ویرگول"
url = "https://virgool.io/karnameh"
[[sections.items]]
icon = ""
title = "وبلاگ"
url = "https://karnameh.com/blog/"
